### ISSUE TITLE
窗口可以調整大小但不能拖放

### ISSUE THREAD

**Issue by KohChia** [nashaofu/dingtalk#1]
比很多其他的版本好的方面就是可以自适应窗口大小调整，但是却没有边框，无法拖动。尝试自己去构建一个带边框的版本，但是 Downloading tmp-25056-0-electron-v1.6.10-linux-x64.zip 直接超时，无法下载。

**Comment by nashaofu** [comment]
@550771955 目前正在写拖拽的功能，周末应该就能上了。下载失败可以把镜像切换到淘宝

**Comment by KohChia** [comment]
我自己修改了一个版本，边框设置为 true，去掉了人为添加的右上角三个按钮。先这样使用了。

**Comment by nashaofu** [comment]
@550771955 新的版本已经发布了,已经完全支持拖拽了，请到[release](https://github.com/nashaofu/dingtalk/releases/latest)页面下载！

**Comment by nashaofu** [comment]
也可以在这里去下载http://54.250.206.210:8080/

**Comment by KohChia** [comment]
Perfect!
