### ISSUE TITLE
ubuntu16.04无法发送图片

### ISSUE THREAD

**Issue by CaryQY** [nashaofu/dingtalk#10]
发送图片之后显示的是一个红色感叹号

**Comment by CaryQY** [comment]
最新版本和上一个版本都有这个问题

**Comment by nashaofu** [comment]
可以粘贴图片，但是没有发出去是吧？我会检查一下看是什么情况，后面再给你答案

**Comment by nashaofu** [comment]
我已经在ubuntu16.04测试过了，是可以发出去的，至于你说的显示红色感叹号应该是网络问题
![image](https://user-images.githubusercontent.com/19303058/30969145-1ab79378-a494-11e7-99de-80cca14a49fc.png)
