### ISSUE TITLE
打开关于之后，关于窗口无法关闭

### ISSUE THREAD

**Issue by GongShengyue** [nashaofu/dingtalk#109]
我使用了Mac版钉钉，打开关于窗口之后一直覆盖在主界面之上，按ESC键也无效，鼠标点击其他位置也无效，想要关闭，只能重启软件，希望可以改进。

**Comment by nashaofu** [comment]
Mac版本没有测试[捂脸]，没钱买不起Mac，不过我会查看，万万没想到Mac用户还有使用的

**Comment by nashaofu** [comment]
问题已经修复，请更行到最新版
