### ISSUE TITLE
播放发送到聊天的视频无法退出

### ISSUE THREAD

**Issue by cxbii** [nashaofu/dingtalk#112]
环境：elementaryOS （ Ubuntu 16.04.3 LTS ）

播放发送到聊天的视频无法退出，必须要关闭钉钉程序才可以恢复。
播放视频的右上角有窗口的关闭等按钮，但是这个是钉钉主窗口的，不是视频窗口的，ESC快捷键也无效。

麻烦抽空看下，谢谢！

**Comment by jackyting825** [comment]
@cxbii 这是个bug,之前我提过了

**Comment by cxbii** [comment]
@jackyting825  没看到，好吧，我的锅。
