### ISSUE TITLE
睡眠恢复/log out 时打开chrome

### ISSUE THREAD

**Issue by xgdgsc** [nashaofu/dingtalk#119]
ubuntu 18.04 下，用的最新appimage，每次睡眠恢复时打开默认浏览器 https://im.dingtalk.com/ ，在manjaro下正常是在自己的窗口打开网页版的。

**Comment by nashaofu** [comment]
已经发布了新版，你可以下载试试

**Comment by xgdgsc** [comment]
新版logout没反应
