### ISSUE TITLE
deepin15.4.1安装最新版本后打不开

### ISSUE THREAD

**Issue by winter110** [nashaofu/dingtalk#12]
之前从deepin商店安装的1.2.1版本，可以正常使用，从github上下载最新版安装更新后就打不开了。是因为缺少了某些依赖吗？

**Comment by nashaofu** [comment]
安装成功了吗？如果能够安装的话应该就是缺少依赖吧。不过deepin没有测试过。等我安装测试确认一下

**Comment by winter110** [comment]
现在装好了，我卸载了，然后直接装的最新版本就好了，不知道怎么回事

**Comment by nashaofu** [comment]
应该是依赖没安装上
