### ISSUE TITLE
Ubuntu 无法切换搜狗输入法

### ISSUE THREAD

**Issue by Patrick0308** [nashaofu/dingtalk#127]
环境ubuntu18
版本2.0.7
启动包 dingtalk-2.0.7-x86_64.AppImage
想切换到搜狗输入法无反应

**Comment by nashaofu** [comment]
只有这个软件会这样吗？感觉不应该出现啊

**Comment by Patrick0308** [comment]
sublime也有问题，其他软件都是好的

**Comment by Patrick0308** [comment]
vscode也是用electron的吧，没问题
