### ISSUE TITLE
外围加个浅蓝色或者灰色边框，不然在白色背景下是这样～

### ISSUE THREAD

**Issue by zuohuadong** [nashaofu/dingtalk#13]
![image](https://user-images.githubusercontent.com/11203929/31527759-0f9d0e86-b002-11e7-8698-7b56ac7ca8ea.png)

**Comment by nashaofu** [comment]
好的，周末发一个版本 @zuohuadong

**Comment by nashaofu** [comment]
[添加边框，以显示出窗口应用形状，简单修复钉邮第一次打开会加载不出来的BUG](https://github.com/nashaofu/dingtalk/commit/11171504584771d761dc65a4a3dc5b57d041a167)已经添加了边框
