### ISSUE TITLE
系统设置可不可以加上自定义截图快捷键

### ISSUE THREAD

**Issue by leiy88** [nashaofu/dingtalk#133]
强制占用CTRL + ALT + A 不能改。与我系统设置shutter冲突， 不小心按到快捷键后导致gnome cpu经常飙到70%+， 原因不明。
App版本：2.0.7
系统版本：18.04 LTS

**Comment by leiy88** [comment]
而且附送的这个截图功能双屏下无法工作， 只能截1.1屏（上下分屏的上半屏+下半屏的title bar）

**Comment by leiy88** [comment]
> 修改网络错误页面，支持快捷键设置，2018-02-07
更新截图功能，支持多显示器截图，目前确认支持Ubuntu16，Ubuntu17不支持，其他Linux系统未测试，其中使用了shortcut-capture模块来实现截图；修复设置页面不修改快捷键时，点击保存时提示错误的BUG，2018-03-03

这两个升级貌似并没有生效啊。。

**Comment by leiy88** [comment]
![image](https://user-images.githubusercontent.com/19524201/47199027-fa758000-d3a1-11e8-9c04-bda84da48982.png)

**Comment by nashaofu** [comment]
设置界面在托盘那里可以点出来，在里面可以修改快捷键的
![image](https://user-images.githubusercontent.com/19303058/47265896-9699b580-d561-11e8-910d-61c58deba1e4.png)
