### ISSUE TITLE
Ubuntu 18.10无法运行

### ISSUE THREAD

**Issue by yupengfei** [nashaofu/dingtalk#136]
Ubuntu 18.10
Gnome 3.30.1
64-bit
输入dingtalk命令，提示
Segmentation fault (core dumped)

**Comment by sluongng** [comment]
https://github.com/electron/electron/issues/13972

**Comment by sluongng** [comment]
https://github.com/nashaofu/dingtalk/pull/137 this pull request should fix it

**Comment by yupengfei** [comment]
fixed
