### ISSUE TITLE
下拉框显示为黑色

### ISSUE THREAD

**Issue by twilroad** [nashaofu/dingtalk#14]
![image](https://user-images.githubusercontent.com/5193767/31528940-a0cb34a4-b008-11e7-8b31-5acc3d0513b9.png)
如图所示。

**Comment by nashaofu** [comment]
鼠标放到下拉框也会不显示文字吗？或者新打开这个界面还会有这个现象吗？

**Comment by zuohuadong** [comment]
不会显示，重新打开界面也是如此。
点击黑色区域可以看到选项卡在变

**Comment by nashaofu** [comment]
这个感觉是显卡渲染的问题，我这边是没有这个情况的

**Comment by twilroad** [comment]
奇怪的是，其他弹出组件就不会：
![image](https://user-images.githubusercontent.com/5193767/31540243-b9ae29ce-b03d-11e7-9193-b67275d05baf.png)

**Comment by zuohuadong** [comment]
显卡 为AMD  APU～
