### ISSUE TITLE
2.0.8版本图标模糊

### ISSUE THREAD

**Issue by yupengfei** [nashaofu/dingtalk#141]
![screenshot from 2018-11-09 15-05-25](https://user-images.githubusercontent.com/1784570/48248157-2c25b800-e431-11e8-9633-cfc231bd0a79.png)

**Comment by xiaotiantian1132** [comment]
我还以为就我一个人 原来都这样 卸载重装两次

**Comment by nashaofu** [comment]
抱歉，太自信了，没有测试，我会尽快修复的

**Comment by nashaofu** [comment]
我会尽快修复的

**Comment by xiaoweb** [comment]
同问题

**Comment by luoyesiqiu** [comment]
同问题

**Comment by nashaofu** [comment]
已经修复这个问题了
