### ISSUE TITLE
CPU长时间占用高

### ISSUE THREAD

**Issue by guoxiaoqiao** [nashaofu/dingtalk#148]
![image](https://user-images.githubusercontent.com/3011645/48900454-5fcefc00-ee8d-11e8-8991-6bf05b6f93cb.png)

**Comment by guoxiaoqiao** [comment]
系统Ubuntu 18.04.1 64位，钉钉版本：2.0.9

**Comment by muyan9** [comment]
用sysinternals系列工具监测发现，cpu占用相对高的时候，确实钉钉的动作频繁，有几点可疑，可惜不能上图：

1、尝试在c:根目录和系统目录和一些看似不相关的目录尝试创建文件，比如C:\Users\desktop.ini、C:\Windows\System32\drivers\etc\hosts

2、读取注册表行为偶尔频率很高，看起来读取的键值好像也有跟钉钉表面不想关的，HKCU\SOFTWARE\Policies\Chromium、HKCU\SOFTWARE\Microsoft\SystemCertificates\trust\Certificates

3、钉钉开启的几个进程中，有至少3个进程，经常会频繁的开启和关闭线程，且有个普遍规律，线程通常在开启33秒后被关闭，目测了十几个线程都是这样，本人认为这一定不是巧合



目前发现的就以上几点，如果有后续再补充

**Comment by nashaofu** [comment]
感谢关注，有可能是使用的相关技术存在缺陷

**Comment by muyan9** [comment]
不好意思，我上面的测试是基于win10  官方下载版本6.0.8
粗看这个源码不认识啊   是官方版本的吗   如果不是，发在这里就不合适了
