### ISSUE TITLE
钉盘中的文件不能下载

### ISSUE THREAD

**Issue by leogorden** [nashaofu/dingtalk#150]
在钉盘的文件列表页面中，直接下载某文件会打开浏览器[https://space.dingtalk.com/attachment/mdown?biztype=file&bizid=574026750&objectid=829353343](https://space.dingtalk.com/attachment/mdown?biztype=file&bizid=574026750&objectid=829353343)，但是不能下载，望后续版本能有机会解决，感谢作者的付出

**Comment by leogorden** [comment]
使用环境 deepin 15.7和15.8

**Comment by nashaofu** [comment]
应该已经修复了，可以下载试试：https://github.com/nashaofu/dingtalk/releases/latest

**Comment by leogorden** [comment]
好的，谢谢

**Comment by jesoonluo** [comment]
@nashaofu 钉盘批量下载好像还是有同样问题，ubuntu17.10， 感谢作者大大。
