### ISSUE TITLE
恕我小人之心，强烈怀疑此钉钉有把用户电脑当肉鸡挖矿嫌疑

### ISSUE THREAD

**Issue by guoxiaoqiao** [nashaofu/dingtalk#153]
![gpu](https://user-images.githubusercontent.com/3011645/49142759-8335f300-f334-11e8-86a3-a8ae4c0e780e.png)
![default](https://user-images.githubusercontent.com/3011645/49142760-8335f300-f334-11e8-87a4-da27817afd03.png)
![cpu](https://user-images.githubusercontent.com/3011645/49142762-83ce8980-f334-11e8-8708-530d834137ca.png)

本人钉钉是从本代码库下载的二进制版本，使用钉钉后电脑经常发热，检查后发现钉钉占用大量资源，当然不是一开启钉钉就会，出现这种情况没啥规律，但是很经常。
经过分析，钉钉启动后CPU和GPU占用率都很高，非常怀疑二进制版本的钉钉有利用用户电脑挖矿。

之前反馈过类似问题，作者的回复是GPU进程用于截图
https://github.com/nashaofu/dingtalk/issues/152
https://github.com/nashaofu/dingtalk/issues/148

**Comment by nashaofu** [comment]
看来你是被吓怕了，欢迎审核代码，每一次提交记录都在的，请拿出实锤

**Comment by guoxiaoqiao** [comment]
那GPU的占用怎么来的

**Comment by guoxiaoqiao** [comment]
我下的是二进制包，打包时加代码很容易

**Comment by nashaofu** [comment]
你可以下载源码，自己编译，看看是否存在，就算编译加东西，我都是用ci打包的，打包工具也是开源的

**Comment by nashaofu** [comment]
![image](https://user-images.githubusercontent.com/19303058/49160435-b5aa1500-f361-11e8-820c-84fbdfe8e9b6.png)
如图是vscode程序启动之后的进程，同样有gpu，vscode同样使用electron开发，你总不能说vscode在用你电脑挖矿吧
同样chrome运行时进程中也有gpu
![image](https://user-images.githubusercontent.com/19303058/49160708-4da7fe80-f362-11e8-8bb8-a255e08385cc.png)
图形界面不使用gup渲染我就奇怪了

质疑可以，但是不能只靠猜测

**Comment by guoxiaoqiao** [comment]
就算我小人之心，此问题也不用关那么快。即使不是在挖矿，资源占用那么高，那程序也有bug，作为一个程序员，完全不提也不找原因，匆匆把问题关了，不合常理。

**Comment by xgdgsc** [comment]
https://github.com/electron/electron/issues/11908 electron本身有可能造成这种，你硬件加速关了试试

**Comment by nashaofu** [comment]
我只是前端开发，很少直接去调用系统底层的东西，所以有很多都不是很明白，优化什么的有点无能为力
