### ISSUE TITLE
能否修复Deepin下托盘图标和消息提示

### ISSUE THREAD

**Issue by buchijiang** [nashaofu/dingtalk#154]
用Deepin商店安装的钉钉，然后发现提示升级，就来此下了deb升级，发现托盘图标有问题，消息提醒也有问题，望大佬修复一下。
deepin版本15.8

**Comment by nashaofu** [comment]
2.0.9版本吗？

**Comment by dzzzzzy** [comment]
2.0.9 deb版的，托盘左键单击不会显示主窗口，而是和右键单击一样显示的是选项列表。

**Comment by buchijiang** [comment]
@nashaofu 对的，是最新版的2.0.9，你可以虚拟机上试一下，当然我也可以配合测试

**Comment by buchijiang** [comment]
![image](https://user-images.githubusercontent.com/13143897/49265615-d1aad500-f48d-11e8-9065-d22c63a584fa.png)
那个齿轮就是钉钉托盘图标
双击图标也不会弹出主窗体

**Comment by wyy0117** [comment]
请问消息提示钉钉图标会闪烁吗？我的不会闪烁，同deepin158，应用商店里显示版本是1.5.9，不知道在钉钉里面怎么看版本号，没有更新到最新版，可以帮助测试，支持大佬。

**Comment by wyy0117** [comment]
已更新到最新版2.0.9，图标显示
![default](https://user-images.githubusercontent.com/19330823/49278051-a5f41300-f4be-11e8-8f1d-f4476cefd982.png)，而且来消息无闪烁，只在桌面右上角提示一下来了消息，然后没了，如果错过提示，图标又不闪烁，基本意识不到来了消息。

**Comment by nashaofu** [comment]
好的，我会看一下的

**Comment by nashaofu** [comment]
问题已经确定了，是electron3.0的bug，2.0就没有问题

**Comment by buchijiang** [comment]
@nashaofu 那不换2.0能解决这个问题吗？

**Comment by wyy0117** [comment]
@buchijiang 其实我更关心的是能不能来消息图标闪烁，毕竟来了消息如果没看到，图标也没有动静那消息基本就一直错过了。不过一切都要根据作者的意愿来，毕竟能有一个linux版的已经很不错了，默默支持作者，能为作者提供测试反馈可能就是我唯一能为作者做的了。

**Comment by nashaofu** [comment]
@wyy0117 哇，很感动！我会考虑你们的需求的，我也给electron提了issue，看他们怎么解决之后我再看是否换回2.0

**Comment by buchijiang** [comment]
electron不会无视deepin的问题吧，理论上跟debian同出一脉，debian应该也有这个问题，亦或者是桌面环境的锅？静静等待结果吧

**Comment by wyy0117** [comment]
关于消息闪烁，我在网上查了一下，跟我天真的想法一样，设置图片透明，不知道能不能用在钉钉里面，https://www.cnblogs.com/meteoric_cry/p/7123325.html，大佬有时间可以看下。

**Comment by zazcoder** [comment]
辛苦作者 这个问题真的很重要，常常错过公司发的重要消息

**Comment by nashaofu** [comment]
好的，周末跟你们解决

在 2018年12月7日，10:51，zazcoder <notifications@github.com<mailto:notifications@github.com>> 写道：


辛苦作者 这个问题真的很重要，常常错过公司发的重要消息

**Comment by nashaofu** [comment]
已经修复啦，去下载2.0.10版本就好了

**Comment by wyy0117** [comment]
刚到公司就下载了最新版，图标已恢复正常，但是来消息还是没有闪烁，我看了一下源码，现在有消息好像是使用了一张右下角有个小点的图片，但实际上这张图片并没有显示，有可能是deepin的问题。大佬有群吗？加群可以好沟通一点。

**Comment by buchijiang** [comment]
图标确实可以了，如果能修复楼上说的问题，那就更nice了

**Comment by userfhy** [comment]
对的 deepin15.8 图标显示正常
来消息仔细看：发现右下角有一个小点 但不会闪烁

**Comment by wyy0117** [comment]
我改了一点点代码，代码写的不好还请不要笑话。图标闪烁是可以做到的，原理就是使用2张图片交替显示，想要像qq一样闪烁只需要把现有的消息图片替换成‘透明’的就可以了，公司美工下班了，明天给我图，现在是默认图和有消息的图交替显示形成闪烁效果，有时间可以看下。
