### ISSUE TITLE
libappindicator

### ISSUE THREAD

**Issue by Aquarian-Age** [nashaofu/dingtalk#157]
系统openSUSE 15.0

没有什么能提供 libappindicator，而它为 dingtalk-2.0.10-134.x86_64 所需
系统里面这个软件是已经安装了的而且不止一个版本 还是提示没有什么能提供 libappindicator

---

然而试了一下安装成功了

**Comment by nashaofu** [comment]
成功安装了吗？

**Comment by Aquarian-Age** [comment]
@

> 成功安装了吗？

是的 所以 就此关闭了 感谢～

**Comment by run27017** [comment]
libappindicator 与 Launchpad 有关，可能是触摸板。我是台式机，就没去管了。
