### ISSUE TITLE
文件下载完 后，没有相应的提示～

### ISSUE THREAD

**Issue by zuohuadong** [nashaofu/dingtalk#16]
![image](https://user-images.githubusercontent.com/11203929/31530253-bf59e02e-b011-11e7-9d1e-c09456e03815.png)

没有提示，也没有打开文件夹的按钮～～

**Comment by nashaofu** [comment]
这个我会想办法看如何提示，最好能和PC效果一致

**Comment by nashaofu** [comment]
已经添加了文件下载进度查看功能。下载文件时，右上角会出现进度条，并且点击开之后会出现文件下载列表，并且应用图标上也会显示进度
