### ISSUE TITLE
deepin下消息提醒红点是白色的

### ISSUE THREAD

**Issue by buchijiang** [nashaofu/dingtalk#160]
![image](https://user-images.githubusercontent.com/13143897/50061297-c23fc180-01d9-11e9-9f47-18f70ce1ab3f.png)
应该不是什么大问题，下个版本修复就行
我想问一下，怎么能先临时解决一下？

**Comment by nashaofu** [comment]
我准备换图标，换好了就发一个版本，可以在安装目录下去修改resources目录下的asar文件，把里面的解压出来，替换图片就好了

**Comment by buchijiang** [comment]
Thank you
