### ISSUE TITLE
加密消息暂时不支持显示，快到手机版或者桌面版钉钉查看

### ISSUE THREAD

**Issue by zgsxwsdxg** [nashaofu/dingtalk#161]
无法查看收到的信息，显示加密
这个如何解决了？

**Comment by nashaofu** [comment]
这个版本不支持加密信息，只能使用手机或者其他方式

**Comment by zgsxwsdxg** [comment]
@nashaofu 谢谢，我想问一下，您会考虑解决这个问题么？

**Comment by buchijiang** [comment]
@zgsxwsdxg 解决不了的，本身网页版就不支持加密信息。只能官方开放接口或者出Linux版
