### ISSUE TITLE
Mac 安装后无法正常显示

### ISSUE THREAD

**Issue by weng-yifeng** [nashaofu/dingtalk#164]
1. Mac 安装包下载后无法正常显示，蓝色空白
2. npm run dev 后也无法正常显示，蓝色空白

Mac 版本：10.14

**Comment by nashaofu** [comment]
你多试几次呢，Linux也有这个问题，好像是网络有问题，我这边Mac是可以的

**Comment by weng-yifeng** [comment]
> 你多试几次呢，Linux也有这个问题，好像是网络有问题，我这边Mac是可以的

换了 4G 网络可以了，确实是网络问题，感谢回复！
