### ISSUE TITLE
Ubuntu 18.04 DingTalk 未读来信提示导致操作界面卡顿

### ISSUE THREAD

**Issue by wzmxd** [nashaofu/dingtalk#176]
卡顿波及任何可视化界面，除非未读提醒被消除。希望可以协助找出原因！

**Comment by N0mansky** [comment]
确实有这样的现象，同18.04

**Comment by xuenhappy** [comment]
一弹出未读消息整个屏幕卡死，按键全无反应，系统ubuntu 18.04.2

**Comment by nashaofu** [comment]
这个问题有点难复现，因为我现在没有主力使用linux，基本只是在开发的时候使用，说以很难发现问题，不过我会尽量看能不能找到原因

**Comment by wzmxd** [comment]
> 这个问题有点难复现，因为我现在没有主力使用linux，基本只是在开发的时候使用，说以很难发现问题，不过我会尽量看能不能找到原因

感谢您还关注这个问题。目前我已经切换回 v2.0.10，此版本很流畅不会造成卡顿。
我会继续期待此问题的解决😀

**Comment by cccthon** [comment]
同样ubuntu18.04， 钉钉版本v2.0.13。一天卡死3-5次左右（只能重启电脑解决）。  
当出现大量未读消息，在消息窗口不断滚动鼠标滚轮。大概率可以复现。

**Comment by nashaofu** [comment]
链接：https://pan.baidu.com/s/1qg6aqnfDoNF3WvnT1aDvMg 
提取码：8pzi 
我这边打包了新版本，你们方便测试一下吗，我这边难复现，打包后文件在百度网盘
