### ISSUE TITLE
新版本更新提示导致无法操作点击

### ISSUE THREAD

**Issue by yancheng199287** [nashaofu/dingtalk#186]
打开钉钉，提示新版本更新小窗口，然后又弹出登录窗口，登录窗口把升级提示窗口挡住了，既不能移动也不能关闭，登录窗口也不能点击，超级严重bug啊。  难道是强制升级吗？  那也不对啊。请解决。

**Comment by nashaofu** [comment]
什么系统？当前版本是多少，应该是可以关闭提示框的，而且也可以关闭更新检测的

**Comment by yancheng199287** [comment]
不能关闭，应该上一个版本。我用的deepin。我只能安装最新的版本解决，要是下一次还是这样，体验不好啊

**Comment by nashaofu** [comment]
大概知道什么原因了，是因为更新提示框跑到主窗口的后面去了，然后导致主窗口不能点击，后面会想办法修复吧，这个说不定是electron的bug，所以不一定能修复好

**Comment by yancheng199287** [comment]
OK

**Comment by nashaofu** [comment]
已经在修复了，下个版本会发布出来

**Comment by echollzq** [comment]
我也是这个问题，你们这个更新太频繁了，导致差不多几天就会提示我更新，可以设置成不显示这个提示吗，等有需要的时候，用户再自己手动更新。
