### ISSUE TITLE
deepin 15.9.3 无法登录

### ISSUE THREAD

**Issue by libsgh** [nashaofu/dingtalk#187]
扫码+密码都无法登录，网络检测
![image](https://user-images.githubusercontent.com/25656088/55769898-fc98db80-5ab4-11e9-8e38-2564d6cbd3dc.png)
在浏览器可以登录

**Comment by nashaofu** [comment]
什么系统，还有使用的版本呢

**Comment by libsgh** [comment]
deepin 15.9.3
2.0.14

**Comment by libsgh** [comment]
![image](https://user-images.githubusercontent.com/25656088/55848457-91680b80-5b7f-11e9-918b-c67a370245d7.png)

**Comment by libsgh** [comment]
又重装了一遍 又好了，可能真是机器的网络问题！
