### ISSUE TITLE
钉钉分类问题

### ISSUE THREAD

**Issue by zuohuadong** [nashaofu/dingtalk#19]
在 Ubuntu 和 Linux mint 下，软件会被归为“其他”分类
而不是互联网 或者 办公

**Comment by nashaofu** [comment]
软件打包的时候倒是有提个category字段，我看看这里是怎样填写，是填写英文还是中文，还有这个字段是否有要求。如果你有了解也可以告诉我

**Comment by zuohuadong** [comment]
抱歉，也不是特别清楚～

**Comment by KohChia** [comment]
Network

**Comment by nashaofu** [comment]
已经修改了配置
