### ISSUE TITLE
2.0.15最新版好像在ubuntu18.04.2环境下无法打开

### ISSUE THREAD

**Issue by JuggerHoo** [nashaofu/dingtalk#192]

**Comment by xuming9** [comment]
2.0.15在deepin15.9.3桌面版也打不开

**Comment by BackFire** [comment]
2.0.15在debian testing的awesome桌面下也打不开

**Comment by yancheng199287** [comment]
2.0.15在deepin 的桌面下也打不开   安装上了，点击启动 啥也没有

**Comment by nashaofu** [comment]
好的，收到了，我今天晚上发一版

**Comment by NullYing** [comment]
打不开+1, Ubuntu 16.04

**Comment by NullYing** [comment]
> 好的，收到了，我今天晚上发一版

可以把更新提示先下了?

**Comment by jay-youngn** [comment]
在 deepin 15.9.3 上有相同的问题

**Comment by nashaofu** [comment]
已撤销

在 2019年4月22日，09:35，白月秋见心 <notifications@github.com<mailto:notifications@github.com>> 写道：


好的，收到了，我今天晚上发一版

可以把更新提示先下了?

**Comment by MichaelPan0905** [comment]
昨天下15版没下完，今天下不了，一看最新2.0.14，吓得我以为自己穿越了（捂脸哭）

**Comment by angelsclare** [comment]
Linux mint19也遇到同样的问题!重新安装能打开,暂时还没有测试关机后重启能否打开

**Comment by killme2008** [comment]
在 elementaory os 上会疯狂 cpu 100%。

**Comment by kaisawind** [comment]
Is it ok now? It can't run on Ubuntu 18.04.2 LTS.
```shell
Ubuntu 18.04.2 LTS \n \l
```

**Comment by JuggerHoo** [comment]
resolved
