### ISSUE TITLE
electron 考虑使用4.0/5.0 ？

### ISSUE THREAD

**Issue by zuohuadong** [nashaofu/dingtalk#193]
貌似其他vue 整合的使用的也都是 2.x 。

但是 angular 的 https://github.com/maximegris/angular-electron 使用了 electron 。

可以一起贡献。

目前在 ubuntu 上使用还是有一些导致系统崩溃的 BUG 。

2.0 迟早还是得淘汰的。

**Comment by nashaofu** [comment]
可以考虑，原来升级到过3，但是在部分linux系统托盘图标显示不出来，后来就降下来了。我当然是希望使用新版本。如果只是托盘图标问题的话，我想应该可以升级吧

**Comment by zuohuadong** [comment]
> 可以考虑，原来升级到过3，但是在部分linux系统托盘图标显示不出来，后来就降下来了。我当然是希望使用新版本。如果只是托盘图标问题的话，我想应该可以升级吧

不知道为啥，我看vue 生态的electron 都是 2.x ， 只有angular 生态的是最新

**Comment by nashaofu** [comment]
已经在使用electron5.0修改了，详情参考[electron-5.0](https://github.com/nashaofu/dingtalk/tree/electron-5.0)分支
