### ISSUE TITLE
1.4.2版本

### ISSUE THREAD

**Issue by xwyjh-qd** [nashaofu/dingtalk#215]
![Uploading image.png…]() 
 模仿1.4.2版本时shortcut-capture.html 引用
<script src="js/shortcut-capture.js"></script>   失败，目录结构是一致的 。

**Comment by nashaofu** [comment]
截图你可以使用我写的插件[shortcut-capture](https://github.com/nashaofu/shortcut-capture)，具体使用方式参考文档

**Comment by xwyjh-qd** [comment]
谢谢回复，我是直接挪用的你写的那个1.4.2版本的东西，但是就下面这个js怎么引用都不成功，这个js也是直接拷贝的你的那个不过css引用成功了。我试了下如果1.4.2版本注释掉这个js的引用的话和我现在的效果是一致的。



shj@cnbisoft.com
 
发件人： nashaofu
发送时间： 2019-06-13 10:30
收件人： nashaofu/dingtalk
抄送： xwyjh-qd; Author
主题： Re: [nashaofu/dingtalk] 1.4.2版本 (#215)
截图你可以使用我写的插件shortcut-capture，具体使用方式参考文档

**Comment by nashaofu** [comment]
具体代码不能看到，我也不能确定什么问题

**Comment by xwyjh-qd** [comment]
非常感谢，如果有空的话你看一下，文档里面是执行的问题，压缩包是代码



shj@cnbisoft.com
 
发件人： nashaofu
发送时间： 2019-06-13 11:38
收件人： nashaofu/dingtalk
抄送： xwyjh-qd; Author
主题： Re: [nashaofu/dingtalk] 1.4.2版本 (#215)
具体代码不能看到，我也不能确定什么问题
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


-----------------------------------------------------------
以下文件通过foxmail发给您。保存时间有限制，请及时提取。
截屏.rar (118.7 M) (有效时间到: 2019/7/13 16:11:41)
链接: http://mail.qq.com/cgi-bin/ftnExs_download?k=0b633665615ea7cd19fc17304263001a0405055505565050195a025c5d4e060302021b5d0100541852510004055b540c50560204646b3288eca5f74b16024035091761&t=exs_ftn_download&code=4c6edc25

**Comment by nashaofu** [comment]
![捕获](https://user-images.githubusercontent.com/19303058/59436931-1e02a480-8e23-11e9-982b-4aca08dedf97.PNG)
不是没加载，而是报错了，你找一下是什么问题吧

**Comment by xwyjh-qd** [comment]
嗯，好的谢谢。看了下是window.source不一样，具体的毛病还在找
