### ISSUE TITLE
更新到2.1.0版时不时地弹JS错误框

### ISSUE THREAD

**Issue by ycrao** [nashaofu/dingtalk#218]
更新到2.1.0版时不时地弹JS错误框，老版本没这问题，不知道是啥问题引起的
环境：Ubuntu LTS 16.04

![image](https://user-images.githubusercontent.com/3280204/59590389-881a9280-911e-11e9-998c-91b163809167.png)

**Comment by nashaofu** [comment]
@ycrao 没错误了吗？

**Comment by ycrao** [comment]
@nashaofu 现在没了，远程引用 `js` 的问题吗？

**Comment by nashaofu** [comment]
应该不是吧，具体问题我也不是很清楚

在 2019年6月18日，16:41，飞扬 <notifications@github.com<mailto:notifications@github.com>> 写道：


现在没了，远程引用 js 的问题吗？
