### ISSUE TITLE
2.1.0版本不能正常显示代办任务

### ISSUE THREAD

**Issue by omaidb** [nashaofu/dingtalk#219]
2.1.0版本不能正常显示代办任务
在pc端添加了任务不显示，手机端能看到新添加的任务。
在手机端添加任务，PC端不显示

**Comment by nashaofu** [comment]
不显示是在电脑端列表中没有，还是没有找到列表

**Comment by omaidb** [comment]
> 不显示是在电脑端列表中没有，还是没有找到列表

在列表中没有

**Comment by nashaofu** [comment]
这个应该是钉钉网页版的问题
