### ISSUE TITLE
2.1.0 版本 CPU 占用过高, 进程经常无故消失

### ISSUE THREAD

**Issue by melonwool** [nashaofu/dingtalk#220]
问题如标题
系统 deepin 15.10.1

**Comment by heirychen** [comment]
mint 19.1 也有遇到相同问题。AppImage 和 deb 包都试过了，都有这问题。

**Comment by nashaofu** [comment]
应该是托盘图标的问题，我下个版本会尝试修复一下

**Comment by alukaa** [comment]
问题+1, 大佬尽快修复下，永久了就变卡，进程无故消息

**Comment by gaozhidf** [comment]
Ubuntu 18.04 加1

**Comment by nashaofu** [comment]
已经发布了新版本了的，可去下载新版本，这个问题也已经修复了的

**Comment by shibingli** [comment]
Linux mint 19.2  装的 2.1.1 CPU经常会百分百。
