### ISSUE TITLE
能否支持Work Report（工作汇报（日志））功能

### ISSUE THREAD

**Issue by bejondshao** [nashaofu/dingtalk#228]
目前最新版v2.1.1不支持日报功能，网页版也不支持。

![image](https://user-images.githubusercontent.com/7846416/61096516-72348f00-a48a-11e9-9afd-74bff08894f0.png)

不知能否支持，还是需要等待网页版支持后会自行支持？谢谢

**Comment by nashaofu** [comment]
这个是网页版不支持的，我这边没法改

**Comment by bejondshao** [comment]
好的，谢谢。
