### ISSUE TITLE
Deepin 15.11 js error

### ISSUE THREAD

**Issue by mixsome** [nashaofu/dingtalk#230]
系统：Deepin 15.11
报错截图：
![图片](https://user-images.githubusercontent.com/22359872/61693255-cd576300-ad61-11e9-89fb-c2f7a3ec26ce.png)
问题重现流程：收到消息后即会弹出

**Comment by nashaofu** [comment]
应用什么版本？升级到最新版本应该就没有这个问题了

**Comment by mixsome** [comment]
是最新版本2.1.1 但是机器重启后这个问题就没有出现
