### ISSUE TITLE
要是能加入截图标记功能和最新群公告功能就好了

### ISSUE THREAD

**Issue by zhangzhengjiao** [nashaofu/dingtalk#243]
9月PC版本更新了群公告功能，老版本都看不了最新的群公告，要是能更新就好啦
还有截图标记功能，现在只支持截图，不支持标记 辛苦！

**Comment by nashaofu** [comment]
截图功能可以改进，但是群公告做不了

**Comment by zhangzhengjiao** [comment]
谢谢采纳😊

发自我的 iPhone

**Comment by annisun** [comment]
很希望增加截图标记功能,不然linux每次截图无法标记很不方便 .基本都没使用钉钉的截图

**Comment by nashaofu** [comment]
最新版本已经支持截图标记

**Comment by annisun** [comment]
liunx发现截图功能好像不生效 16.04版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nashaofu <notifications@github.com>
发送时间: 2020年3月26日 14:24
收件人: nashaofu/dingtalk <dingtalk@noreply.github.com>
抄送: annisun <liyan@ux168.com>, Comment <comment@noreply.github.com>
主题: 回复：[nashaofu/dingtalk] 要是能加入截图标记功能和最新群公告功能就好了 (#243)





 
最新版本已经支持截图标记
