### ISSUE TITLE
能不能帮忙编译一个arm64平台的deb安装包？

### ISSUE THREAD

**Issue by piyaming** [nashaofu/dingtalk#244]
我现在用的平台是 arm 64 的桌面平台系统。也就是传说中国产系统，国产软件。系统是银河麒麟，CPU是飞腾1500A。
肯请帮忙编译一个arm平台的安装包。

**Comment by nashaofu** [comment]
暂时先编译了AppImage的：https://github.com/nashaofu/dingtalk/releases/download/v2.1.1/dingtalk-2.1.1-latest-arm64.AppImage

**Comment by piyaming** [comment]
好的，太感谢了。
已经用上了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nashaofu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月12日(星期六) 晚上10:56
收件人:&nbsp;"nashaofu/dingtalk"<dingtalk@noreply.github.com&gt;;
抄送:&nbsp;"174494886"<174494886@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nashaofu/dingtalk] 能不能帮忙编译一个arm64平台的deb安装包？ (#244)




Closed #244.
