### ISSUE TITLE
钉钉聊天框界面展示问题

### ISSUE THREAD

**Issue by aierweisi** [nashaofu/dingtalk#246]
在某些时候，钉钉的聊天框会出现模糊的情况，请问下是什么原因，最近版本，macos系统，如下图
![image](https://user-images.githubusercontent.com/33406910/66626842-4dd48400-ec2c-11e9-8194-4c8afe2f2774.png)

**Comment by nashaofu** [comment]
这个是mac原生版本，你去给钉钉官方反馈吧。
