### ISSUE TITLE
Ubuntu16.04 无法打开界面

### ISSUE THREAD

**Issue by ummmme** [nashaofu/dingtalk#25]
![2017-11-08 09-46-38](https://user-images.githubusercontent.com/8966854/32527596-c756e9cc-c469-11e7-909f-2cd8aff6a7c4.png)

正常安装后，突然有一天打不开了。如图所示。

**Comment by AkariMarisa** [comment]
这是不是无法连接网络时，打开应用界面的效果

**Comment by ummmme** [comment]
@AkariMarisa 已经确定是无网络连接时打开应用时无任何展示的问题。谢谢

PS：建议加上提示。

**Comment by nashaofu** [comment]
后续会添加这个功能

**Comment by nashaofu** [comment]
已经支持网络错误显示 #37
