### ISSUE TITLE
有新消息时无弹窗或者消息提醒功能

### ISSUE THREAD

**Issue by annisun** [nashaofu/dingtalk#26]
有新消息时无弹窗或者消息提醒功能,能不能在有新消息时增加图标闪动或者提醒新消息呢

**Comment by nashaofu** [comment]
当前已经添加这个功能的，周末我排查一下

**Comment by hippyk** [comment]
我也遇到这个问题，而且web版本身就有这个问题，非常困扰

**Comment by zcldzh** [comment]
现在最新版弹窗提示消息只有你有1条未读消息的提醒，没有消息内容的提示，能加下这个功能吗

**Comment by zhaohongxuan** [comment]
deepin的系统，会有右上角的通知，通知的图标缺失了。
![image](https://user-images.githubusercontent.com/8613196/38478253-275b212e-3bea-11e8-8cf1-1c1c6b4d47ae.png)
而且托盘的通知没有，有时候会错过消息，希望能够修复。
