### ISSUE TITLE
2.1.2 文件下载会连续弹出两次

### ISSUE THREAD

**Issue by jay-youngn** [nashaofu/dingtalk#261]
RT

deepin 15.11 桌面版

**Comment by nashaofu** [comment]
能提供详细一点的信息吗？

**Comment by jay-youngn** [comment]
> 能提供详细一点的信息吗？

就是点击下载文件的时候，会弹出两个文件管理器，取消和保存都会操作两次。
用的 deepin 15.11，不知道是不是系统原因

**Comment by nashaofu** [comment]
确实会出现，下个版本修复

**Comment by cliuyang** [comment]
在dingtalk 2.1.3，Ubuntu19.10的环境下，该问题仍会出现。点击下载时弹出两个文件管理器，且取消和保存都会操作两次。
