### ISSUE TITLE
禁止私聊的群无法打开

### ISSUE THREAD

**Issue by frinkleko** [nashaofu/dingtalk#264]
显示：该群已禁止私聊，请用客户端打开
请问能否增加群方面的功能，使得能够打开禁止私聊的群（非全员禁言）
版本2.12

**Comment by frinkleko** [comment]
![TIM图片20200201195859](https://user-images.githubusercontent.com/32212221/73591754-aa3a1700-452d-11ea-89dd-ed1aa6284442.png)

**Comment by nashaofu** [comment]
这个不能支持，因为是网页版，我这边也不能改动
