### ISSUE TITLE
更新到ubuntu17.10 后 状态栏图标不能显示了 快捷键调用截图功能不能使用了

### ISSUE THREAD

**Issue by DevineLiu** [nashaofu/dingtalk#27]

**Comment by nashaofu** [comment]
应该是electron没有支持，只有等待electron更新支持了

**Comment by DevinXian** [comment]
The screen is dark when doing screenshot...

**Comment by nashaofu** [comment]
最新版已经支持状态栏显示图标了，但截图还是有问题 https://github.com/nashaofu/dingtalk/releases/tag/v1.5.1
