### ISSUE TITLE
不能看直播？

### ISSUE THREAD

**Issue by GwnYn** [nashaofu/dingtalk#273]
苦逼学生要用钉钉上网课但是Linux上的钉钉没有直播？

**Comment by nashaofu** [comment]
不支持的

**Comment by wszqkzqk** [comment]
不支持吗？。。。。。。。。。。。。。。。。。。。

**Comment by wszqkzqk** [comment]
难受。。。。。。。。。。。

**Comment by 474420502** [comment]
一个投入那么大的公司连个跨平台都做不了, 还办公协作. 不是公司要用,  哪里我都不推荐使用钉钉.

**Comment by nashaofu** [comment]
哈哈哈，都是被资本家压迫的。

**Comment by nashaofu** [comment]
哈哈哈，都是被资本家压迫的。

**Comment by flerxu** [comment]
> 哈哈哈，都是被资本家压迫的。

我是做运维的，自从用了这个破玩意儿，每天都睡不好觉。
