### ISSUE TITLE
钉钉启动窗体只有背景色

### ISSUE THREAD

**Issue by citywalki** [nashaofu/dingtalk#280]
![深度截图_plasmashell_20200318100847](https://user-images.githubusercontent.com/11208441/76918556-89712980-6901-11ea-8923-3dc16e6ccb51.png)

用过几天，但是今天打开就是这样了。

**Comment by nashaofu** [comment]
应该是网络有问题，以前很多人反馈这个问题

**Comment by citywalki** [comment]
> 应该是网络有问题，以前很多人反馈这个问题

那有什么办法嘛？

**Comment by nashaofu** [comment]
重启打大法，还有你看看你能不能访问https://im.dingtalk.com/

**Comment by citywalki** [comment]
> 重启打大法，还有你看看你能不能访问https://im.dingtalk.com/

thk  果然第二天又好了。
