### ISSUE TITLE
可否打包一个Windows的版本

### ISSUE THREAD

**Issue by momokoudai** [nashaofu/dingtalk#29]
钉钉桌面版在Windows上不可直视。在1080p 13寸电脑上小的看不见了都。

**Comment by momokoudai** [comment]
经过几次尝试，已经自行编译出Windows版本，非常棒。谢谢作者。
希望后续可以打包Windows版本。

**Comment by nashaofu** [comment]
好的，其实这个版本和windows自身的版本还是有很大差距的

**Comment by momokoudai** [comment]
其实用不了多少功能，如果不是web版老被我不小心关闭掉，用web版就可以了。
他提供的Windows版本在1080p 13寸屏幕上界面小的看着累。
希望能够提供win版本，并且新消息时能够拖盘闪动（显示消息数量也不错）
谢谢
