### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by lifuru1997** [nashaofu/dingtalk#294]
OS:Ubuntu 20.04 LTS
dpkg error log:
The following NEW packages will be installed:
  dingtalk
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3,429 kB of archives.
After this operation, 202 MB of additional disk space will be used.
Get:1 /home/hoastar/dingtalk-2.1.5-latest-amd64.deb dingtalk amd64 2.1.5-182 [3,429 kB]
E: Archive is too short
E: Prior errors apply to /home/hoastar/dingtalk-2.1.5-latest-amd64.deb
debconf: apt-extracttemplates failed: No such file or directory
Selecting previously unselected package dingtalk.
(Reading database ... 166474 files and directories currently installed.)
Preparing to unpack .../dingtalk-2.1.5-latest-amd64.deb ...
Unpacking dingtalk (2.1.5-182) ...
dpkg-deb (subprocess): cannot copy archive member from '/home/hoastar/dingtalk-2.1.5-latest-amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /home/hoastar/dingtalk-2.1.5-latest-amd64.deb (--unpack):
 cannot copy extracted data for './opt/\351\222\211\351\222\211/icudtl.dat' to '/opt/\351\222\211\351\222\211/icudtl.dat.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /home/hoastar/dingtalk-2.1.5-latest-amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by AkariMarisa** [comment]
deb包不完整
