### ISSUE TITLE
聊天窗口不能用右键菜单复制粘贴文字

### ISSUE THREAD

**Issue by KohChia** [nashaofu/dingtalk#3]
直接在浏览器中打开网页版钉钉右键菜单，在几个位置出现不同菜单：

1. 会话列表：点击右键会出现特殊菜单，比如删除或置顶会话之类的
1. 聊天对话窗口选中文字或者文字输入区域，点击右键是可以选择复制粘贴的。
1. 其他区域，点击右键会出现浏览器在网页中的默认右键菜单。

在你这个版本中，会话窗口选中文字或者在底部输入区域，右键点击无效果，只能通过快捷键来复制粘贴。

**Comment by nashaofu** [comment]
@550771955 下个版本将会提供你需要的功能,谢谢反馈!

**Comment by nashaofu** [comment]
@550771955 已经支持右键菜单了 [https://github.com/nashaofu/dingtalk/releases/latest](https://github.com/nashaofu/dingtalk/releases/latest)
