### ISSUE TITLE
可以提供钉钉撤回消息显示嘛？

### ISSUE THREAD

**Issue by kemistep** [nashaofu/dingtalk#300]
这个和官方的pc差一点在哪里？
希望能提供hack有点，比如 钉钉消息撤回显示，这样就更有动力用这个

**Comment by nashaofu** [comment]
这个功能目前做不了，这个项目其实主要是提供给linux用户使用的，因为目前官方Linux版本还没有正式放出来

**Comment by kemistep** [comment]
> 这个功能目前做不了，这个项目其实主要是提供给linux用户使用的，因为目前官方Linux版本还没有正式放出来

谢谢
