### ISSUE TITLE
窗口无法放大缩小

### ISSUE THREAD

**Issue by greenlaw110** [nashaofu/dingtalk#301]
如下图所示, 完全看不到消息发送人的名字:
![image](https://user-images.githubusercontent.com/216930/85201076-d240e000-b33f-11ea-88bc-c0b26103d285.png)

**Comment by nashaofu** [comment]
你使用的是chrome 应用吧？

**Comment by greenlaw110** [comment]
是的

**Comment by nashaofu** [comment]
在[这里](https://github.com/nashaofu/dingtalk/releases)去下载，我的这个不是chrome应用，是桌面软件

**Comment by greenlaw110** [comment]
不好意思啊. 是我弄错了
