### ISSUE TITLE
笨方法实现Windows新消息闪烁功能

### ISSUE THREAD

**Issue by momokoudai** [nashaofu/dingtalk#31]
感谢作者的无私奉献，个人使用中发现Windows下无法闪烁图标，粗糙的实现一下。
1、借用更新badge的方法
main.js - setBadgeCount 方法最后添加 
`ipcRenderer.send('set-tray-flash', count)`
用来发送新消息事件
2、dingtalk.js添加处理
this.$trayIntervalId
this.$trayLight
前面初始化一下

// 设置 tray图标新消息闪动
  onSetTrayFlash () {
    ipcMain.on('set-tray-flash', (e, count) => {
      if (app) {
        if (count > 0) {
          if (this.$trayIntervalId) {
            return
          }
          this.$trayIntervalId = setInterval(() => { // 每0.5秒闪烁一次
            if (this.$trayLight) {
              this.$tray.setImage(path.join(__dirname, '../icon/tray_blank.png'))
              this.$trayLight = false
            } else {
              this.$tray.setImage(path.join(__dirname, '../icon/tray_newmsg.png'))
              this.$trayLight = true
            }
          }, 500)
           this.$tray.setToolTip('钉钉\n您有 ' + count + '条新消息')
        } else {
          clearInterval(this.$trayIntervalId)
          this.$trayIntervalId = null
          this.$tray.setToolTip('钉钉\n 没有未读消息')
          this.$tray.setImage(path.join(__dirname, '../icon/tray_default.png'))
        }
      }
    })
  }
3、用到的图片如下，也可以自己制作，iconfont.cn上随便找图标

![tray_blank](https://user-images.githubusercontent.com/33850943/33166040-d1804fea-d073-11e7-88dd-50a98b889733.png)
![tray_default](https://user-images.githubusercontent.com/33850943/33166041-d1b1fae0-d073-11e7-8239-4acce97df8e3.png)
![tray_newmsg](https://user-images.githubusercontent.com/33850943/33166042-d1fb20da-d073-11e7-8f9f-f218b6a4e49c.png)
![tray_offline](https://user-images.githubusercontent.com/33850943/33166044-d22e4672-d073-11e7-8949-4d278ad87b4b.png)

**Comment by momokoudai** [comment]
额，代码阅读困难，发个截图
![tim 20171207171947](https://user-images.githubusercontent.com/33850943/33707663-1af16df8-db73-11e7-8774-a99da8304821.jpg)

**Comment by nashaofu** [comment]
厉害，我也是这样干的🤝
