### ISSUE TITLE
ubuntu16.04打开软件界面乱码，停留在蓝色界面，不出现扫码界面，不能进行任何操作

### ISSUE THREAD

**Issue by haqiankaka** [nashaofu/dingtalk#313]
rt,请问是电脑环境的问题吗
![Selection_360](https://user-images.githubusercontent.com/27956204/90085908-a5abb200-dd4b-11ea-9919-7f52c6aa458b.png)

**Comment by haqiankaka** [comment]
[
![Selection_360](https://user-images.githubusercontent.com/27956204/90085931-b65c2800-dd4b-11ea-9b52-f291bbf2667c.png)
](url)

**Comment by nashaofu** [comment]
倾向于是网络问题导致的,https://github.com/nashaofu/dingtalk/issues/248

**Comment by nashaofu** [comment]
## 蓝色界面问题排查方案
1. 开浏览器访问http://im.dingtalk.com/, 看是不是能够正常访问，如不能正常访问则是网络问题
2. 如果能正常访问，那么就应该是本软件网络接入权限有问题

**Comment by inmyjs** [comment]
确认是网络问题，我系统是deepin20，前面一直是好的，突然有天启动就是蓝色背景，啥也没有，看楼上说网络问题我才去看系统代理，不知道怎么打开了，关闭后钉钉就正常了

**Comment by thend03** [comment]
我这边也显示了蓝色背景, @nashaofu ,貌似是gtk3主题的问题导致无法显示，~/.config/gtk-3.0/
系统是manjaro kde 20.x  内核是5.10,dingtalk版本是dingtalk-2.1.9-latest-x86_64


os-catalina-gtk会显示如下主题parse error，然后打开就是一个蓝色的界面，没有登陆页
![image](https://user-images.githubusercontent.com/41274496/104295717-c6935180-54fb-11eb-92da-cd5f397f6b2a.png)


然后主题切换到mojave-light-alt不报错，打开仍是蓝色界面
![image](https://user-images.githubusercontent.com/41274496/104295665-b8ddcc00-54fb-11eb-9ea9-5fc4f54a139f.png)

**Comment by nashaofu** [comment]
> 我这边也显示了蓝色背景, @nashaofu ,貌似是gtk3主题的问题导致无法显示，~/.config/gtk-3.0/
> 系统是manjaro kde 20.x 内核是5.10,dingtalk版本是dingtalk-2.1.9-latest-x86_64
> 
> os-catalina-gtk会显示如下主题parse error，然后打开就是一个蓝色的界面，没有登陆页
> ![image](https://user-images.githubusercontent.com/41274496/104295717-c6935180-54fb-11eb-92da-cd5f397f6b2a.png)
> 
> 然后主题切换到mojave-light-alt不报错，打开仍是蓝色界面
> ![image](https://user-images.githubusercontent.com/41274496/104295665-b8ddcc00-54fb-11eb-9ea9-5fc4f54a139f.png)

你有按这个步骤排查吗？https://github.com/nashaofu/dingtalk/issues/313#issuecomment-679443364

**Comment by whenevertobefc** [comment]
确实是代理的问题，本来是用的系统代理，不知道怎么就变成了手动设置代理。

im.dingtalk.com是可以访问的，后面看的时候在qv2ray的路由设置里设置了im.dingtalk.com直联，以为不是代理的问题
刚才把代理关了，然后命令行启动会有报错，不过不影响功能

**Comment by thend03** [comment]
> > 我这边也显示了蓝色背景, @nashaofu ,貌似是gtk3主题的问题导致无法显示，~/.config/gtk-3.0/
> > 系统是manjaro kde 20.x 内核是5.10,dingtalk版本是dingtalk-2.1.9-latest-x86_64
> > os-catalina-gtk会显示如下主题parse error，然后打开就是一个蓝色的界面，没有登陆页
> > ![image](https://user-images.githubusercontent.com/41274496/104295717-c6935180-54fb-11eb-92da-cd5f397f6b2a.png)
> > 然后主题切换到mojave-light-alt不报错，打开仍是蓝色界面
> > ![image](https://user-images.githubusercontent.com/41274496/104295665-b8ddcc00-54fb-11eb-9ea9-5fc4f54a139f.png)
> 
> 你有按这个步骤排查吗？[#313 (comment)](https://github.com/nashaofu/dingtalk/issues/313#issuecomment-679443364)

确实是代理的问题，本来是用的系统代理，不知道怎么就变成了手动设置代理。

im.dingtalk.com是可以访问的，后面看的时候在qv2ray的路由设置里设置了im.dingtalk.com直联，以为不是代理的问题
刚才把代理关了，然后命令行启动会有报错，不过不影响功能
