### ISSUE TITLE
所以怎么启动呢... 后端用户表示不会启动

### ISSUE THREAD

**Issue by cabbagehao** [nashaofu/dingtalk#325]
npm run pack 结束后呢?

**Comment by nashaofu** [comment]
命令运行成功之后会在项目的release目录下生成对应平台的二进制安装包，然后安装就好了！

**Comment by cabbagehao** [comment]
好的谢谢。 只是启动起来后中文显示乱码， 不过也能满足一些基本需求，感谢。
