### ISSUE TITLE
深度操作系统截图得到是黑色图片

### ISSUE THREAD

**Issue by doremifaJ** [nashaofu/dingtalk#327]
深度操作系统截图得到是黑色图片

**Comment by doremifaJ** [comment]
关闭gpu加速，类似在app.on('ready')之前设置app.disableHardwareAcceleration()
或者参考https://www.coder.work/article/6805022
不知能否生效

**Comment by nashaofu** [comment]
你的系统是什么版本？我这边安装一下，方便测试

**Comment by doremifaJ** [comment]
> 你的系统是什么版本？我这边安装一下，方便测试

Deepin: https://www.deepin.org/zh/download/

**Comment by nashaofu** [comment]
最新的版本吗？

2020年11月26日 09:47，jazzwsr <notifications@github.com<mailto:notifications@github.com>> 写道：



你的系统是什么版本？我这边安装一下，方便测试

Deepin: https://www.deepin.org/zh/download/

**Comment by doremifaJ** [comment]
> 最新的版本吗？

我用的beta版，你可以试下看：http://packages.deepin.com/deepin-cd/releases/20Beta/
