### ISSUE TITLE
deepin 系统下 总是自动退出如何解决

### ISSUE THREAD

**Issue by Jamesccvv** [nashaofu/dingtalk#332]
deepin 系统下 总是自动退出如何解决

**Comment by nashaofu** [comment]
有报错吗？

**Comment by Jamesccvv** [comment]
> 有报错吗？

没有啊，挂在那一会自己就退了，一天要登录N次

**Comment by justthinkyouth** [comment]
linux fedora下也是，一会就退出了

**Comment by nashaofu** [comment]
deepin什么版本系统

**Comment by Jamesccvv** [comment]
> deepin什么版本系统

15.11 桌面版，挂一会自己就没了，版本低的就好点没那么快退出，最新的版本退出的很快

**Comment by wukunmeng** [comment]
deepin 控制台错误信息
`Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
段错误`
段错误--是不是有内存泄露

**Comment by nashaofu** [comment]
这周在外面骑行，后面一点再处理

发自我的华为手机


-------- 原始邮件 --------
发件人： wukunmeng <notifications@github.com>
日期： 2020年12月23日周三 20:11
收件人： nashaofu/dingtalk <dingtalk@noreply.github.com>
抄送： nashaofu <diaocheng@outlook.com>, Comment <comment@noreply.github.com>
主 题： Re: [nashaofu/dingtalk] deepin 系统下 总是自动退出如何解决 (#332)

deepin 控制台错误信息
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank" 段错误

―

**Comment by nashaofu** [comment]
我在deepin下测试没有发现这个问题，虽然输出了警告，但没有自动退出，你们检查一下是否存在软件冲突，或者提供更多报错信息

**Comment by wukunmeng** [comment]
> 我在deepin下测试没有发现这个问题，虽然输出了警告，但没有自动退出，你们检查一下是否存在软件冲突，或者提供更多报错信息

下面是在终端运行 dingtalk-2.1.9-latest-x86_64.AppImage 控制台打印的信息
`Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"`
`段错误`
刚开始只打印了 第一行的警告，不会立即退出，过一段时间就闪退了。
控制台上 多了“段错误” 估计是有内存泄露的问题吧
deepin桌面版本：15.11
现在切换到版本：dingtalk-2.0.7-x86_64.AppImage    在使用这个版本中没有出现闪退的问题。
