### ISSUE TITLE
Desktop Notifications 设置项不起作用

### ISSUE THREAD

**Issue by tangxinfa** [nashaofu/dingtalk#34]
该选项关闭后仍然会发送新消息通知，暂时先用 dunst 把钉钉的通知忽略了。

OS: Arch Linux
Notification Daemon:  notify-osd 或 dunst
Desktop: i3wm

**Comment by jing2uo** [comment]
同样的问题：
OS: Debian Sid
Desktop：mate 1.20.1
Notification Daemon：mate-notification-daemon

关闭桌面通知权限依然有通知弹出。

之前用了几天gnome，也有相同的问题，3.28
