### ISSUE TITLE
软件打开后卡在蓝底窗口

### ISSUE THREAD

**Issue by skystalkerrc** [nashaofu/dingtalk#342]
可能和electron有关，其他基于electron的软件也是同样时间段出现无法刷新界面的问题。
参考这个fix: https://github.com/klaussinani/tusk/pull/332

**Comment by nashaofu** [comment]
参考这个https://github.com/nashaofu/dingtalk/issues/313

**Comment by skystalkerrc** [comment]
> 参考这个#313

谢谢提醒！４天前出问题后一直使用网页钉钉，刚才试着打开app发现可以正常使用。
