### ISSUE TITLE
无法在Kali虚拟机安装该软件

### ISSUE THREAD

**Issue by angle5037** [nashaofu/dingtalk#343]
请求楼主帮助

**Comment by nashaofu** [comment]
安装报什么错误？

**Comment by angle5037** [comment]
─# sudo dpkg -i dingtalk-2.1.9-latest-amd64.deb   
正在选中未选择的软件包 dingtalk。
(正在读取数据库 ... 系统当前共安装有 322448 个文件和目录。)
准备解压 dingtalk-2.1.9-latest-amd64.deb  ...
正在解压 dingtalk (2.1.9) ...
dpkg: 依赖关系问题使得 dingtalk 的配置工作不能继续：
 dingtalk 依赖于 libappindicator3-1；然而：
  未安装软件包 libappindicator3-1。

dpkg: 处理软件包 dingtalk (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 desktop-file-utils (0.26-1) 的触发器 ...
正在处理用于 mailcap (3.68) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
在处理时有错误发生：
 dingtalk

**Comment by angle5037** [comment]
环境是Kali最新版，镜像源在官源基础上加了清华、中科大、阿里，已更新软件源

**Comment by angle5037** [comment]
我嘗試自行手動安裝所需依賴庫，已經正常安裝，謝謝！

**Comment by ljy-002** [comment]
@angle5037 你的Dingtalk是否可以正常起动？
[我提出了一个类似的问题](https://github.com/nashaofu/dingtalk/issues/432)

**Comment by angle5037** [comment]
> @angle5037 你的Dingtalk是否可以正常起动？ [我提出了一个类似的问题](https://github.com/nashaofu/dingtalk/issues/432)

我的可以正常启动，基本功能OK，缺失一些Windows上新版本的功能，体验了一段时间后还是放弃了，不够丝滑。
不过，虚拟机跟WSL环境可能还是有差异的
