### ISSUE TITLE
在托盘点击显示界面后，直接跳转到搜索联系人

### ISSUE THREAD

**Issue by Corezcy** [nashaofu/dingtalk#360]
如题，请问如何设置取消啊

**Comment by nashaofu** [comment]
没有复现，还会出现这个问题吗

**Comment by Corezcy** [comment]
> 没有复现，还会出现这个问题吗

还是会啊，Ubuntu18.04的系统，关闭界面后点击托盘里的图标，选择显示窗口，打开了界面，鼠标光标focus到搜索联系人那一栏。
![Screenshot-20210521082857-1108x1374](https://user-images.githubusercontent.com/33271784/119064797-c3125880-ba0e-11eb-973b-5cf69bb9010d.png)

**Comment by nashaofu** [comment]
为啥关闭了，是因为其他问题导致的吗？

**Comment by Corezcy** [comment]
> 为啥关闭了，是因为其他问题导致的吗？

感觉可能是个例的小小bug，就不把这个问题开着了，毕竟还是很好用很方便的！！！
程序员何苦为难程序员呢
