### ISSUE TITLE
希望可以在linux的版本上查看日志,写日志

### ISSUE THREAD

**Issue by Hfywtias** [nashaofu/dingtalk#367]
如题,我们经常使用日志,但是写日志看日志的时候只能用手机查看

**Comment by Hermes777** [comment]
写日志没问题啊。。只是写文档似乎没有实现

**Comment by Hfywtias** [comment]
不应该啊,点击日志会弹窗 Confirmation Message  具体内容是The current version is too low to open this session.我的是2.1.9版本,最新版的更新里好像没有提及写日志的

**Comment by Hfywtias** [comment]
> 不应该啊,点击日志会弹窗 Confirmation Message 具体内容是The current version is too low to open this session.我的是2.1.9版本,最新版的更新里好像没有提及写日志的

已完成,在聊天界面不能查看日志.需要进**工作**选项卡,进日志里读写日志.打扰了
