### ISSUE TITLE
windows 10 下截图功能无效

### ISSUE THREAD

**Issue by consatan** [nashaofu/dingtalk#377]
按快捷键或者用鼠标点，都无法唤出截图功能
鼠标会滚动一下（加载效果），然后又变回正常鼠标
这个功能只支持 linux 系统吗？

系统：windows 10 pro 64位 (10.0.19043.1202)
dingtalk：2.1.11
使用 exe 安装（下面这个链接）
https://github.com/nashaofu/dingtalk/releases/download/v2.1.11/dingtalk-2.1.11-latest.exe

**Comment by nashaofu** [comment]
升级到新版本就可以了
