### ISSUE TITLE
Ubuntu20.04 安装包报错

### ISSUE THREAD

**Issue by yangliuan** [nashaofu/dingtalk#382]
sudo dpkg -i dingtalk-2.1.12-latest-amd64.deb 
Selecting previously unselected package dingtalk.
(Reading database ... 377466 files and directories currently installed.)
Preparing to unpack dingtalk-2.1.12-latest-amd64.deb ...
Unpacking dingtalk (2.1.12) ...
Setting up dingtalk (2.1.12) ...
chmod: cannot access '/opt/dingtalk/chrome-sandbox': No such file or directory
Processing triggers for mailcap (3.68) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

错误提示
chmod: cannot access '/opt/dingtalk/chrome-sandbox': No such file or directory

实际生成的目录是/opt/钉钉

**Comment by nashaofu** [comment]
安装这个 [dingtalk-2.1.12-latest-i386.deb](https://github.com/nashaofu/dingtalk/releases/download/v2.1.12/dingtalk-2.1.12-latest-i386.deb)

**Comment by nashaofu** [comment]
发了最新版https://github.com/nashaofu/dingtalk/releases/tag/v2.1.13，我在虚拟机中没问题
