### ISSUE TITLE
DingTalk for Linux does not support video conferencing

### ISSUE THREAD

**Issue by niklassemmler** [nashaofu/dingtalk#389]
I installed the most recent DingTalk version 2.1.12 AppImage on Ubuntu. The software runs fine. 

However, when I go to the video-conferencing tab, I see the following picture: 

![image](https://user-images.githubusercontent.com/1880943/144814118-db642eff-add0-4fcd-b69b-f27de8853023.png)

The message is: "DingTalk web edition not supported, please Download Desktop DingTalk"

Is Video-conferencing not supported for linux?

**Comment by nashaofu** [comment]
This version is based on the web version, so it cannot be supported

**Comment by niklassemmler** [comment]
Thanks, good to know.
