### ISSUE TITLE
ubuntu20.04 启动报错

### ISSUE THREAD

**Issue by hehuang139** [nashaofu/dingtalk#394]
环境：ubuntu20.04
安装： 2.1.13-amd64

12.11.10版本都试过都能打开，13版本安装后无法打开，
直接用命令dingtalk启动，报错
[69706:1216/113329.612759:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018

**Comment by nashaofu** [comment]
先不要升级，目前发现打成二进制包后有问题

**Comment by nashaofu** [comment]
发了新版本了，你下载试试https://github.com/nashaofu/dingtalk/releases/tag/v2.1.13

**Comment by hehuang139** [comment]
可以了
