### ISSUE TITLE
状态栏图标

### ISSUE THREAD

**Issue by SeptemberHX** [nashaofu/dingtalk#4]
需要修复一下状态栏图标，在KDE 5.10.4上，状态栏图标如下所示：
![image](https://user-images.githubusercontent.com/18042424/28600991-25e5136c-71e8-11e7-8ce0-3d1ecd1e7cfe.png)
最左边那个，看起来像是图标太大了，只显示了部分，希望提供各种大小的图标，然后在状态栏上做一下大小适配。

然后就是鼠标移动到状态栏上，显示的是 electron，这里应该显示dingtalk吧。

还有一个建议，希望状态栏能够左键单击打开钉钉窗口，而不是现实菜单

最后。。能不能添加记住密码/自动登录的功能？

多谢作者了～

**Comment by nashaofu** [comment]
由于是在Ubuntu上进行的测试，所以其他的桌面系统没有进行测试，不过下一个版本尽量修复， @SeptemberHX 你是使用的什么版本的Linux(我只使用过Ubuntu)

**Comment by SeptemberHX** [comment]
openSUSE Tumbleweed，我试了一下，贴了一张20x20的图片进去作为状态栏图标，刚好
![image](https://user-images.githubusercontent.com/18042424/28650808-b3e2ebd0-72b0-11e7-9ed0-8c9b14480340.png)

**Comment by nashaofu** [comment]
@SeptemberHX 如果你有兴趣，可以提交pr

**Comment by SeptemberHX** [comment]
我不太清楚其他系统的状态栏图标是怎么处理的，我只是简单粗暴的加了一个20x20的图片当做状态栏图标，这样可能会导致其他发行版本的状态栏图标模糊，还是需要简单的测试一下。

**Comment by nashaofu** [comment]
@SeptemberHX 应该可以的，我这个图标比较打
