### ISSUE TITLE
截屏快捷键如何修改？

### ISSUE THREAD

**Issue by giyyapan** [nashaofu/dingtalk#40]
是否提供了修改截屏快捷键的功能？ctrl+alt+a 会和我的一些其他软件冲突
如果不方便修改，可否直接关闭此功能？

谢谢！

**Comment by nashaofu** [comment]
目前没有支持修改，并且也没有支持关闭，后面会考虑修改

**Comment by giyyapan** [comment]
好的，辛苦了

2018-01-02 20:19 GMT+08:00 nashaofu <notifications@github.com>:

**Comment by nashaofu** [comment]
最新版本已经支持截图了 #51

**Comment by nashaofu** [comment]
最新版本已经支持修改快捷键了 https://github.com/nashaofu/dingtalk/releases/tag/v1.5.1
