### ISSUE TITLE
日志和审批功能间接性无法使用

### ISSUE THREAD

**Issue by MistEO** [nashaofu/dingtalk#41]
在`工作`中，`日志`和`审批`等几个项目之间多切换几次就会提示Error网络错误
![2018-01-03 17-11-42](https://user-images.githubusercontent.com/18511905/34514666-679d1abc-f0a9-11e7-8b67-63536ded5374.png)

点击`重试`，有时候能连上，需要重新登陆，有时候进程就直接崩溃了。

网络错误和重试进程崩溃都很频繁，随便多点几下就会出现

系统是Ubuntu 16.04 64位

提示网络错误时终端没有任何输出，点击`重试`崩溃时的输出如下
![2018-01-03 17-22-30](https://user-images.githubusercontent.com/18511905/34514919-b17ed3fe-f0aa-11e7-9390-e14ec7882c53.png)

**Comment by nashaofu** [comment]
已经发布了新版本，看看还会出现这个问题吗

**Comment by MistEO** [comment]
试了一下好像没问题了，辛苦啦
