### ISSUE TITLE
linux下小程序打开报错&无法打开

### ISSUE THREAD

**Issue by tianqo** [nashaofu/dingtalk#419]
这两天要考试，会用到云课堂里的小程序发的试卷，但打开小程序则会立马报错：
![图片](https://user-images.githubusercontent.com/68796895/180604966-e3ed285f-40f4-4ae7-99ed-f082a4c2bdce.png)
每次报错结果都一样，无论是否是其他小程序，都为以下内容：
`dingtalk://dingtalkclient/action/open_micro_app?appId=5488&corpId=ding1a0fff9832c1447635c2f4657eb6378f&que…00114544_2798897%26source%3Dnotice&slide_panel_option=%7B%22width%22%3Anull%2C%22showAppPage%22%3Afalse%7D`
请问是否是因为系统下载的包有问题还是程序本身问题。

**Comment by nashaofu** [comment]
应该是不能打开的，你可以使用网页版试试，网页版不支持，我这个版本就不支持。

**Comment by tianqo** [comment]
> 应该是不能打开的，你可以使用网页版试试，网页版不支持，我这个版本就不支持。

确实不行，那我再找找其他办法吧。
