### ISSUE TITLE
还在维护吗，近期打开会弹出浏览器页面“系统维护页面”

### ISSUE THREAD

**Issue by maoxuner** [nashaofu/dingtalk#423]
版本：2.1.21-1
近期打开程序会弹出以下浏览器页面，提示维护，需要下载最新版钉钉

https://page.dingtalk.com/wow/z/dingtalk/default/HP4mfiwxPyDiCphdkjJy

**Comment by lianchengwu** [comment]
我这边也显示这个

**Comment by lfpdev** [comment]
有官方的提供的linux版本了

**Comment by nashaofu** [comment]
应该是官方关闭了web版，所以我这个项目应该要结束啦

**Comment by maoxuner** [comment]
> 应该是官方关闭了web版，所以我这个项目应该要结束啦

---

网页版确实也跳转到那个维护页面了。感谢大佬们的贡献 @nashaofu
