### ISSUE TITLE
屏幕截图黑屏，钉邮打不开

### ISSUE THREAD

**Issue by yinjy** [nashaofu/dingtalk#45]
点击屏幕截图，整个屏幕黑屏
钉邮一直加载中

**Comment by nashaofu** [comment]
什么系统

**Comment by yinjy** [comment]
ubuntu 17.10
钉邮可以用了,大概是我网络问题
截屏问题我用别的截图软件如shutter也遇到了

**Comment by nashaofu** [comment]
ubuntu 17.10截图electron还没有支持，拿到的截图资源有问题
