### ISSUE TITLE
[Query]会不会支持截图功能？

### ISSUE THREAD

**Issue by januslo** [nashaofu/dingtalk#5]
RT.

**Comment by nashaofu** [comment]
要支持截图的话，只能定义全局快捷键，在聊天对话框添加会比较麻烦

**Comment by januslo** [comment]
或者可以考虑在toolbar 和 快捷键的模式

**Comment by januslo** [comment]
remark : may refer: https://github.com/YIXUNFE/blog/issues/64

**Comment by nashaofu** [comment]
下一个版本会考虑加入这个功能

**Comment by nashaofu** [comment]
正在考虑开发截图功能，下一个周末应该可以搞定，很感谢 @januslo 推荐的文章，很有帮助

**Comment by nashaofu** [comment]
由于周末看了s7比赛，没能及时更新，现在已经支持屏幕截图了，快捷键为`ctrl+alt+a`

**Comment by januslo** [comment]
厉害👍

发自我的 iPhone
