### ISSUE TITLE
1.50最新版的截图有bug

### ISSUE THREAD

**Issue by q158467234** [nashaofu/dingtalk#51]
我的是mint，最新版的截图有bug，直接卡死，什么都动不了，只能kill进程

**Comment by frui85** [comment]
我的也是,ubuntu 16.04 截图弹出一个对话框外框然后卡死,直接kill掉重进,之前版本是好的.  
如果能直接调用Shutter 也不错,希望最终能实现原版或者qq那种截图标记的效果,支持开发者!

**Comment by l0o0** [comment]
ubuntu 17.10 也出现同样的结果，直接卡死，鼠标失焦，什么也点不了

**Comment by nashaofu** [comment]
已经更新了一个版本，修复了bug， @l0o0 但是Ubuntu17截图是没有效的，截出来的图片是黑色，这是由于electron截图不支持造成的
