### ISSUE TITLE
1.5.1 ubuntu已经解决截图bug,但是还有些问题,截图界面被宽幅被压缩了

### ISSUE THREAD

**Issue by frui85** [nashaofu/dingtalk#52]
触发截图界面后 显示截图底层会偏移并压缩. 
但是截图选择框内没事,不过仍然会造成最右侧有部分截图不能完全被截取到
[pic](http://codebak.ufile.ucloud.com.cn/选区_001.png?UCloudPublicKey=ucloudyongyi.wang%40360che.com14401528150001059281328&Signature=IdNRDOU2X%2B37Fy8HzHMrFX529OQ%3D&Expires=1518142297)

**Comment by nashaofu** [comment]
你应该是用的Ubuntu吧，这个是因为Ubuntn桌面会让窗口定位为(0,0)的时候，以dock为开始，目前也没有找到好的方法解决

**Comment by nashaofu** [comment]
截图问题已经修复，你可以下载最新版试试
