### ISSUE TITLE
多屏显示时, 截图存在的问题

### ISSUE THREAD

**Issue by zhqiyi** [nashaofu/dingtalk#53]
1. 无论焦点在那个屏幕上, 截图Screen都会集中到笔记本的屏幕上
2. 快捷按下后, 截屏被激活,同时electron的调试页也会被激活
![web_ding_bug_screenshot](https://user-images.githubusercontent.com/2107075/36007711-81e883f6-0d7e-11e8-888b-4ded85ea80e0.png)

**Comment by nashaofu** [comment]
什么系统？chrome调试页会出来？用的哪个版本的钉钉，升级到最新版试试

**Comment by nashaofu** [comment]
发了一个新版本，你看看问题解决没有，实测Ubuntu16没问题
