### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by webcssphp** [nashaofu/dingtalk#55]
17 error Linux 4.10.0-38-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error dingtalk@1.5.2 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the dingtalk@1.5.2 build script 'node scripts/build.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dingtalk package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node scripts/build.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dingtalk
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dingtalk
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nashaofu** [comment]
node 版本应该低了吧，你升级到8吧
