### ISSUE TITLE
邮箱问题

### ISSUE THREAD

**Issue by senkawu** [nashaofu/dingtalk#6]
希望可以优化左下角钉邮、管理可以从默认浏览器打开。

**Comment by nashaofu** [comment]
这个人看了一下邮箱打开的机制，应该可以实现这个功能

**Comment by jackyting825** [comment]
恩,希望可以加入钉邮功能,现在点击钉邮是没反应的,点击很多次貌似会提示服务器错误

**Comment by nashaofu** [comment]
正在寻找解决方法，打开浏览器去阅读邮件需要使用到token去登陆，而目前获取不到token

**Comment by nashaofu** [comment]
已经支持邮箱打开了

**Comment by jackyting825** [comment]
更新了.已经可以支持邮箱了.可以关闭这个问题了
