### ISSUE TITLE
2.0版本深度系统无法启动

### ISSUE THREAD

**Issue by gengqiupeng** [nashaofu/dingtalk#60]
![image](https://user-images.githubusercontent.com/13412304/37807043-50c72072-2e7e-11e8-8bea-350da98e1d2f.png)
钉钉进程已经启动，但是右下角没有图标，也没有弹出界面。

操作系统 deepin 15
钉钉版本：2.0

**Comment by gengqiupeng** [comment]
退回到1.5.2仍然遇到相同问题。怀疑可能是系统的问题。之前1.5.2是正常的

**Comment by jay-youngn** [comment]
@gengqiupeng 1.5.2正常

**Comment by gengqiupeng** [comment]
回退到系统软件商店的1.4.2，终于正常了

**Comment by jay-youngn** [comment]
@gengqiupeng 我用apt purge dingtalk把2.0卸掉，重新安装了1.5.2，注销之后再进来就可以用1.5.2了（同样的方法对2.0无效）

**Comment by dr2009** [comment]
+1.

**Comment by nashaofu** [comment]
应该是我在开发环境的存储的应用配置文件为最新的，但是你们安装的电脑上还是旧版本，所以导致配置项出了问题报错了，现在已经更新了一个版本，应该没有问题了，如有问题请再反馈！很抱歉，给你们造成了困扰。#61 #62

**Comment by jay-youngn** [comment]
@nashaofu  2.0.1可以打开了，但是最小化到托盘之后双击不能显示窗口，不知道其他人有没有这个情况

`apt policy dde-dock`
dde-dock:
  已安装：4.5.9-2
  候选： 4.5.9-2
  版本列表：
 *** 4.5.9-2 500
        500 http://packages.deepin.com/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status

`OS:` Deepin 15.5 unstable
`Kernel:` x86_64 Linux 4.14.0-deepin2-amd64
`Uptime:` 2h 48m
`Packages:` 2477
`Shell:` bash
`Resolution:` 1366x768
`DE:` Deepin 15.5
`WM:` Deepin WM
`WM Theme:` deepin
`GTK Theme:` deepin [GTK2/3]
`Icon Theme:` deepin
`CPU:` Intel Core i5-4210U @ 4x 2.401GHz [42.0°C]
`GPU:` Mesa DRI Intel(R) Haswell Mobile 
`RAM:` 1562MiB / 7722MiB

**Comment by gengqiupeng** [comment]
@ginnerpeace deepin同样的情况，最小化到托盘无法打开，但是1.4.2是可以打开的。2.0.1最小化到任务栏是可以打开的

**Comment by nashaofu** [comment]
可能是我用了双击事件，而你们的桌面系统支支持单击，以前版本的是单击出现窗口

**Comment by jay-youngn** [comment]
嗯嗯，没太多影响，上班时候钉钉窗口一直开着，而且右键显示窗口是ok的。
@nashaofu 一直在更新，很棒了

**Comment by frui85** [comment]
我也遇到同样问题，直接 sudo /usr/local/bin/dingtalk  可以打开但是无法输入中文，估计是输入相关的功能造成的。我是ubuntu 16.04  按了搜狗了

**Comment by nashaofu** [comment]
我在Ubuntu16上测试是没有问题的

**Comment by jing2uo** [comment]
单击双击托盘图标都无法显示窗口的问题在mate 1.20上也有。debian sid

**Comment by frui85** [comment]
@nashaofu 启动后能输入中文吗？ubuntu16.04 用root权限直接命令行起dingtalk服务可以起来，中文输入法无法使用

**Comment by frui85** [comment]
2.0.1同样问题

**Comment by jay-youngn** [comment]
@luckydog85 安利你 deepin

**Comment by jackyting825** [comment]
建议还是改成在托盘单击图标就能打开主界面吧 .双击事件好像很多桌面环境不兼容哦

**Comment by jay-youngn** [comment]
我在公司用的台式机上，2.0.1最小化到托盘又是可以单击、或双击打开的，之前打不开可能是因为系统原因
@nashaofu 

dde-dock版本还是4.5.9-2

**Comment by nashaofu** [comment]
现在双击单击我都加上了的

**Comment by nashaofu** [comment]
输入中文感觉时你们系统问题吧，我这边没遇到 @luckydog85

**Comment by ccpwcn** [comment]
我的深度系统（Deepin 15.5）上，安装2.0.4版本，基本运行正常，但是邮箱打不开。
![_ _20180516100943](https://user-images.githubusercontent.com/5465756/40092713-64baa00c-58f1-11e8-8f09-64010978d9f3.png)
