### ISSUE TITLE
2.0版本在linux mint 18.3上启动不了

### ISSUE THREAD

**Issue by lylwo317** [nashaofu/dingtalk#61]
在命令行启动报了下面的错误
(node:11514) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.setting.keymap.shortcut-capture.join is not a function
(node:11514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by midaug** [comment]
我也遇到了. 进程里有,界面不出现,和上面相同的错误~
![image](https://user-images.githubusercontent.com/16200096/37807496-b6fce82a-2e80-11e8-97e4-7bcb30351ee6.png)

**Comment by inuxor** [comment]
```
(node:4282) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.setting.keymap.shortcut-capture.join is not a function
(node:4282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
kubuntu 18.04同样

**Comment by jing2uo** [comment]
debian sid 遇到相同情况，汇报一下。

**Comment by nashaofu** [comment]
应该是我在开发环境的存储的应用配置文件为最新的，但是你们安装的电脑上还是旧版本，所以导致配置项出了问题报错了，现在已经更新了一个版本，应该没有问题了，如有问题请再反馈！很抱歉，给你们造成了困扰。

**Comment by nashaofu** [comment]
#60

**Comment by jing2uo** [comment]
修复好快，赞一个
