### ISSUE TITLE
建议菜单项增加"关于"菜单

### ISSUE THREAD

**Issue by terrencewei** [nashaofu/dingtalk#70]
标识当前软件版本号和release地址,每次更新完更新成功没有都不确定,看不到当前软件版本是多少

现有菜单项:
显示窗口
屏幕截图
设置
退出

建议增加为:
显示窗口
屏幕截图
设置
**关于**
退出

**Comment by terrencewei** [comment]
而且现在有个bug, 我已更新为2.0.1版本.每次启动的时候还是提示我有最新的版本是否要更新
环境: Ubuntu14.04.3

**Comment by nashaofu** [comment]
已经添加关于页面了，更新问题也已经修复了，https://github.com/nashaofu/dingtalk/releases
