### ISSUE TITLE
自己编译安装方式变了吗

### ISSUE THREAD

**Issue by deemoding** [nashaofu/dingtalk#73]
我 `npm i && npm run build` 了之后，并没有重新生成linux-unpacked文件夹（内的文件）

**Comment by nashaofu** [comment]
还要运行`npm run release`才会打包

**Comment by deemoding** [comment]
我运行了npm rum release之后，报了[这个错误](https://cfp.vim-cn.com/cbdZY)。
不知道这个错误有没有什么影响。
npm 5.7.1      node 9.9.0
顺便问下，能不能只构建linux-unpack，不构建其他版本（deb包，appImage之类的）

**Comment by nashaofu** [comment]
最后的错误没有影响的，那个是部署到github时报错的，去掉错误信息可以去掉package.json文件中的`build.publish选项`，只想打包linux-unpack，应该修改`build.linux.target`为`dir`就好了吧，具体我没有试，可参考：https://github.com/electron-userland/electron-builder

你可以修改配置为如下的试试
```json
{
    "appId": "com.electron.dingtalk",
    "productName": "钉钉",
    "copyright": "Copyright © year nashaofu",
    "directories": {
      "output": "release"
    },
    "files": [
      "dist/**/*",
      "icon/*"
    ],
    "mac": {
      "target": "dmg",
      "icon": "icon/icon.icns",
      "category": "public.app-category.instant-messaging"
    },
    "win": {
      "icon": "icon/icon.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "target": "dir",
      "icon": "icon",
      "category": "InstantMessaging;Network"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "artifactName": "dingtalk-${version}.${ext}",
      "allowToChangeInstallationDirectory": true,
      "displayLanguageSelector": true,
      "language": 2052
    }
  }
```

**Comment by tangxinfa** [comment]
建议提供手工编译运行的文档，个人是 Archlinux，没有合适的安装包，现在都是自动取最新的 tag，然后编译、运行

**Comment by nashaofu** [comment]
@tangxinfa 你能提供一份你编译的的文档内容吗？我不是很清楚你用的编译的方式，还是和我一样用node打包吗？

**Comment by deemoding** [comment]
确实对使用没什么影响。不过，我后来觉得appimage很好用，决定只生成appimage。修改后的 [package.json](https://cfp.vim-cn.com/cbfcW)

不过还是有些错误，那个GitHub Personal Access Token is not set的错误还在。而且，Linux-unpack貌似是默认生成的，我这样写配置还是会生成。这是不是意味着，那个unpack什么时候都会生成一个?
[运行时log](https://cfp.vim-cn.com/cbfcZ)
[完整的log](https://cfp.vim-cn.com/cbfdb)

**Comment by nashaofu** [comment]
GitHub Personal Access Token is not set是我部署到GitHub release的token，所以在你们本地运行时会报这个错，对于打包出来的文件完全没有问题

**Comment by tangxinfa** [comment]
@nashaofu 

我用的 archlinux，虽然 aur 也有 dingtalk 包，但是因为想学一下相关开发，现在完全走源代码方式编译、运行最新 tag 版本：

    git remote update
    latest=$(git tag -l | grep -E "^v" | tail -1)
    git checkout $latest
    echo "build dingtalk $latest ..."
    npm install
    npm run build
    npm start

不知道我上面的步骤对不对，最好是能够提供正式的文档说明。

**Comment by nashaofu** [comment]
自己构建的方式可参考[手动构建](https://github.com/nashaofu/dingtalk#%E6%89%8B%E5%8A%A8%E6%9E%84%E5%BB%BA)，如有问题再沟通 @tangxinfa
