### ISSUE TITLE
记住密码的bug

### ISSUE THREAD

**Issue by jackyting825** [nashaofu/dingtalk#76]
登录的时候不管是否取消记住密码的复选框,退出后下次重新打开默认都会记住密码的.密码在这个文件里面,除非手动删除这个配置文件~/.config/dingtalk/config.json重新打开输入框才不会记住密码

**Comment by nashaofu** [comment]
新版本已经修复了 #81

**Comment by jackyting825** [comment]
@nashaofu,好的,辛苦啦,刚下载新版本的试了,修复了..另外发现最近几个版本的钉邮一直都打不开的,一直是sso了
