### ISSUE TITLE
申请特性：透盘图标单击toggle的功能

### ISSUE THREAD

**Issue by jing2uo** [nashaofu/dingtalk#77]
谢谢@nashaofu的工作，体验非常棒，issue的处理也超级快，赞一下 XD

托盘图标点击切换显示隐藏的特性可否加一下，详细描述是——
如果窗口没显示，点击显示
如果窗口被其他应用压着了，点击是显示到最前
如果窗口处于激活状态，点击隐藏

具体可以参考goldendict，不知道好不好实现~

**Comment by nashaofu** [comment]
前面两个会支持的，后面的一个会考虑，但不一定会实现

**Comment by jing2uo** [comment]
2.0.4，mate desktop 1.20.1前两个已经实现了，最后一个不做就不做咯。我关issue吧
