### ISSUE TITLE
ubuntu17.10，消息通知过多，导致清理时卡死

### ISSUE THREAD

**Issue by fliaping** [nashaofu/dingtalk#79]
版本2.0.3，ubuntu17.10，消息通知不会自动消失，一直在顶部的通知栏，然后通知栏变得很长，Clear All的时候就卡住了，只能重启

**Comment by tianyouhui** [comment]
16.04也有该问题哦，不过不会卡死而已。Ubuntu 16.04+Gnome3，从2.0.3开始，太多消息了。
![screenshot from 2018-04-16 09-50-45](https://user-images.githubusercontent.com/1204612/38786751-7227872a-415c-11e8-9adc-8edc64858842.png)

**Comment by nashaofu** [comment]
后面会更换提示消息的库

**Comment by qhongchen** [comment]
= = 为啥我没有这个通知
