### ISSUE TITLE
ubuntu16.04安装失败

### ISSUE THREAD

**Issue by subcrew** [nashaofu/dingtalk#84]
> ~/Downloads sudo dpkg -i dingtalk_2.0.4_amd64.deb                              
(Reading database ... 436731 files and directories currently installed.)
Preparing to unpack dingtalk_2.0.4_amd64.deb ...
Unpacking dingtalk (2.0.4-94) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive dingtalk_2.0.4_amd64.deb (--install):
 cannot copy extracted data for './opt/\351\222\211\351\222\211/icudtl.dat' to '/opt/\351\222\211\351\222\211/icudtl.dat.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 dingtalk_2.0.4_amd64.deb

> ~/Downloads uname -i                                                                                                                                                          
x86_64

**Comment by leohan1992** [comment]
同遇到

**Comment by jackyting825** [comment]
使用AppImage的包呢?

**Comment by nashaofu** [comment]
从错误信息来看应该是文件损坏了

**Comment by leohan1992** [comment]
@jackyting825 使用appimage包可以。
